### ISSUE TITLE
Icon Not Square, won't display in Plugin Installer

### ISSUE THREAD

**Issue by MidoriKami** [Bluefissure/NoKillPlugin#6]
![image](https://github.com/Bluefissure/NoKillPlugin/assets/9083275/4d704a23-0305-4edf-a0ed-533fc216f583)

![image](https://github.com/Bluefissure/NoKillPlugin/assets/9083275/dd71963d-5c66-4142-8eda-4b56c4efb8ec)

**Comment by Bluefissure** [comment]
Dear chatgpt fixed it https://chat.openai.com/share/d11de125-fb2f-4cc3-940a-fb02f7bfbc71
Waiting for https://github.com/goatcorp/DalamudPluginsD17/pull/1985 but seems not passing the CI

**Comment by MidoriKami** [comment]
PR was merged, however as goat noted https://github.com/goatcorp/DalamudPluginsD17/pull/1985#issuecomment-1585785830
It won't take effect until there is a PR with a higher version.

I'll close this issue for now as no further action is required on this topic.
