### ISSUE TITLE
Update for 7.0

### ISSUE THREAD

**Issue by iDevLA** [Bluefissure/NoKillPlugin#9]
Needs to be updated for Dawntrail. I am assuming just a dalumudapi change?

**Comment by phanlongtran** [comment]
Same, needs update

**Comment by YsEmei** [comment]
They updated the ACT version for 7.0, but it doesn't seem to work. Still closes my game on lobby error.
https://github.com/Bluefissure/NoKill_ACT_Plugin

**Comment by Bluefissure** [comment]
> Needs to be updated for Dawntrail. I am assuming just a dalumudapi change?

The queue mode sig was not found but I thing it can be removed / temporarily disabled as the queue is stable.
I'll try to update it asap, got a little busy irl these days.

> They updated the ACT version for 7.0, but it doesn't seem to work. Still closes my game on lobby error. https://github.com/Bluefissure/NoKill_ACT_Plugin

It's not for 7.0, but for 6.5x (Intl and CN).

**Comment by Bluefissure** [comment]
Trying to test https://github.com/Bluefissure/NoKillPlugin/commit/d8200a891a535b0f69494fc2c73db77ea42e5db8 out but game is down >.<

**Comment by Bluefissure** [comment]
Should be good to go, if there's anything that's broken just let me know.
